import Head from "next/head";
import { BsFillMoonStarsFill } from "react-icons/bs";
import {
  AiFillLinkedin,
  AiFillFacebook,
  AiFillInstagram,
  AiFillGithub,
  AiFillMail,
} from "react-icons/ai";
import Image from "next/image";
import sou from "../public/dev-ed-wave.png";
import { useState } from "react";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>BENZINA SOULEF</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <main className="bg-white px-10">
          <section className="min-h-screen">
            <nav className="py-10 mb-12 flex justify-between">
              <h1 className="text-xl ">mobile developer </h1>
              <ul className="flex items-center">
                <li>
                  <BsFillMoonStarsFill
                    onClick={() => setDarkMode(!darkMode)}
                    className="cursor-pointer text-2xl"
                  />
                </li>
                <li>
                  <a
                    className="bg-gradient-to-r  from bg-cyan-500 to-teal-500 text-black px-4 py-2 rounded-md ml-8"
                    href="#"
                  >
                    Resume
                  </a>
                </li>
              </ul>
            </nav>
            <div className="text-center p-10">
              <h2 className="text-5xl py-2 text-teal-600 font-medium">
                benzina soulef
              </h2>
              <h3 className="text-2xl py-2"> developer mobile and web</h3>
              <p className="text-md py-3 leading-8 text-gray-800">
                benzina soule fdhjDJSNJ SQNVBCJ DIUR O51534 8SDJHZJ ZJIU
                EIOUEIEI sjkjdskjd jjskjksdjs jsdjhsdjhsjd sjdjdhjs
              </p>
            </div>
            <div className="text-5xl flex justify-center gap-16 text-blue-300 py-3">
              <AiFillLinkedin />
              <AiFillMail />
              <AiFillGithub />
              <AiFillFacebook />
              <AiFillInstagram />
            </div>
            <div className="mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 relative overflow-hidden mt-20 md:h-96 md:w-96">
              <Image src={sou} />
            </div>
          </section>
          <section>
            <div>
              <h3 className="text-3xl py-1">service I offer</h3>
              <p className="text-md py-2 leading-8 text-gray-800">
                since the biginning of my journey as a developer, I work for
                <span className="text-teal-500"> startup </span>
                with team of developers
              </p>
            </div>
          </section>
        </main>
      </div>
    </div>
    // </>
  );
}
